### ISSUE TITLE
Need to add automatic pull request tests for continuous integration

### ISSUE THREAD

**Issue by EvanOman** [EvanOman/Kaggle-Titanic#5]
Github says so

**Comment by harma051** [comment]
Where does it say this?

**Comment by EvanOman** [comment]
"Avoid bugs by automatically running your tests.
Continuous integration can help catch bugs by running your tests automatically.
Merge your code with confidence using one of our continuous integration providers."

https://github.com/integrations/feature/build

**Comment by harma051** [comment]
Aha. Well, we'd actually have to have tests for that to work.

**Comment by EvanOman** [comment]
The null test will suffice for now
